**UNIT 1: MENGUMPULKAN DATA (J.62DMI00.004.1)**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('/content/Dataset_Warmindo.xlsx')
df

,id,invoice_id,tanggal_transaksi,customer_id,nama_produk,jenis_produk,kategori_produk,quantity,harga_jual,jenis_pembayaran,jenis_pesanan,nilai_penjualan
0,1,1,2022-04-11,44,Indomie Ayam Spesial,mie-kuah,makanan,2,9000,QRIS-OVO,Dine-In,18000
1,2,2,2022-08-01,10,Indomie Ayam Spesial,mie-kuah,makanan,2,9000,CASH,Delivery,18000
2,3,3,2022-04-03,62,Indomie Rasa Soto Betawi,mie-kuah,makanan,1,10000,QRIS-OTHERS,Delivery,10000
3,4,4,2022-03-19,48,Indomie Rasa Soto Padang,mie-kuah,makanan,3,10000,CASH,Dine-In,30000
4,5,5,2022-04-29,87,Indomie Rasa Sop Buntut,mie-kuah,makanan,2,10000,QRIS-OVO,Dine-In,20000
...,...,...,...,...,...,...,...,...,...,...,...,...
494,495,495,2022-05-17,11,Indomie Baso Sapi,mie-kuah,makanan,1,9000,CASH,Delivery,9000
495,496,496,2022-06-06,55,Indomie Goreng Spesial,mie-goreng,makanan,1,9000,QRIS-GOPAY,Delivery,9000
496,497,497,2022-07-14,25,Indomie Goreng Rendang,mie-goreng,makanan,2,9000,QRIS-GOPAY,Delivery,18000
497,498,498,2022-08-22,39,Indomie Goreng Pedas,mie-goreng,makanan,2,9000,QRIS-DANA,Delivery,18000
498,499,499,2022-06-21,79,Indomie Soto Mie,mie-kuah,makanan,1,9000,QRIS-OVO,Dine-In,9000

**Bisnis Understanding:**
Optimasi Strategi Operasional dan Penjualan Warmindo Melalui Analisis Perilaku Konsumen dan Efisiensi Transaksi.

**UNIT 2: MENELAAH DATA (J.62DMI00.005.1)**

In [9]:
# Ringkasan informasi dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 499 non-null    int64
 1   invoice_id         499 non-null    int64
 2   tanggal_transaksi  499 non-null    datetime64[ns]
 3   customer_id        499 non-null    int64
 4   nama_produk        499 non-null    object
 5   jenis_produk       499 non-null    object
 6   kategori_produk    499 non-null    object
 7   quantity           499 non-null    int64
 8   harga_jual         499 non-null    int64
 9   jenis_pembayaran   499 non-null    object
 10  jenis_pesanan      499 non-null    object
 11  nilai_penjualan    499 non-null    int64
dtypes: datetime64[ns](1), int64(6), object(5)
memory usage: 46.9+ KB

In [28]:
# Tipe data awal
print(df.dtypes)

id                            int64
invoice_id                    int64
tanggal_transaksi    datetime64[ns]
customer_id                   int64
nama_produk                  object
jenis_produk                 object
kategori_produk              object
quantity                      int64
harga_jual                    int64
jenis_pembayaran             object
jenis_pesanan                object
nilai_penjualan               int64
dtype: object

In [8]:
# Jumlah baris dan kolom
df.shape

(499, 12)

In [6]:
df.describe()

,id,invoice_id,tanggal_transaksi,customer_id,quantity,harga_jual,nilai_penjualan
count,499.000000,499.000000,499,499.000000,499.000000,499.000000,499.000000
mean,250.000000,250.000000,2022-05-03 12:15:52.304609280,48.016032,1.953908,9438.877756,18440.881764
min,1.000000,1.000000,2022-01-01 00:00:00,1.000000,1.000000,9000.000000,9000.000000
25%,125.500000,125.500000,2022-03-01 00:00:00,22.000000,1.000000,9000.000000,10000.000000
50%,250.000000,250.000000,2022-05-10 00:00:00,48.000000,2.000000,9000.000000,18000.000000
75%,374.500000,374.500000,2022-07-03 12:00:00,72.500000,3.000000,10000.000000,27000.000000
max,499.000000,499.000000,2022-08-30 00:00:00,100.000000,3.000000,10000.000000,30000.000000
std,144.193157,144.193157,NaN,28.521811,0.796503,496.748002,7575.722958

In [10]:
# Cek Missing Value
df.isnull().sum()

id                   0
invoice_id           0
tanggal_transaksi    0
customer_id          0
nama_produk          0
jenis_produk         0
kategori_produk      0
quantity             0
harga_jual           0
jenis_pembayaran     0
jenis_pesanan        0
nilai_penjualan      0
dtype: int64

In [11]:
# Cek duplikat data
df.duplicated().sum()

np.int64(0)

In [12]:
# Mengecek jumlah total baris yang duplikat
jumlah_duplikat = df.duplicated().sum()
print(f"Jumlah baris duplikat: {jumlah_duplikat}")

# Menampilkan baris yang duplikat jika ada
if jumlah_duplikat > 0:
    print("\nBaris yang duplikat:")
    display(df[df.duplicated(keep=false)])
else:
    print("\nTidak ada data duplikat dalam dataset.")

Jumlah baris duplikat: 0

Tidak ada data duplikat dalam dataset.

**UNIT 3: MEMVALIDASI DATA (J.62DMI00.006.1)**

In [22]:
df_clean = df.copy()

In [23]:
# hapus duplikat
df_clean = df_clean.drop_duplicates()

In [24]:
# Penanganan id, invoice_id, dan costumer_id dari type data int64 menjadi object
id_columns = ['id', 'invoice_id', 'customer_id']
for col in id_columns:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype(str)

In [19]:
# Penanganan tipe data tanggal
if 'tanggal_transaksi' in df.columns:
    df['tanggal_transaksi'] = pd.to_datetime(df['tanggal_transaksi'])

In [29]:
print(df_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 499 non-null    object
 1   invoice_id         499 non-null    object
 2   tanggal_transaksi  499 non-null    datetime64[ns]
 3   customer_id        499 non-null    object
 4   nama_produk        499 non-null    object
 5   jenis_produk       499 non-null    object
 6   kategori_produk    499 non-null    object
 7   quantity           499 non-null    int64
 8   harga_jual         499 non-null    int64
 9   jenis_pembayaran   499 non-null    object
 10  jenis_pesanan      499 non-null    object
 11  nilai_penjualan    499 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 46.9+ KB
None

In [27]:
#Tipe data dalam dataset setelah penyesuaian
print(df_clean.dtypes)

id                           object
invoice_id                   object
tanggal_transaksi    datetime64[ns]
customer_id                  object
nama_produk                  object
jenis_produk                 object
kategori_produk              object
quantity                      int64
harga_jual                    int64
jenis_pembayaran             object
jenis_pesanan                object
nilai_penjualan               int64
dtype: object

**UNIT 4: MENENTUKAN OBJEK DATA (J.62DMI00.007.1)**

In [32]:
# Objek data yang dipilih
print("Kolom terpilih:", df_clean.columns.tolist())

Kolom terpilih: ['id', 'invoice_id', 'tanggal_transaksi', 'customer_id', 'nama_produk', 'jenis_produk', 'kategori_produk', 'quantity', 'harga_jual', 'jenis_pembayaran', 'jenis_pesanan', 'nilai_penjualan']

**UNIT 5: MENGKONSTRUKSI DATA (J.62DMI00.009.1)**

In [36]:
# Membuat dim_tanggal
min_date = df_clean['tanggal_transaksi'].min().floor('D')
max_date = df_clean['tanggal_transaksi'].max() + pd.offsets.MonthEnd(0)

date_range = pd.date_range(start=min_date, end=max_date, freq='D')

dim_tanggal = pd.DataFrame({'Date': date_range})
dim_tanggal['Tahun'] = dim_tanggal['Date'].dt.year
dim_tanggal['BulanNo'] = dim_tanggal['Date'].dt.month
dim_tanggal['Bulan'] = dim_tanggal['Date'].dt.strftime('%b')
dim_tanggal['TahunBulan'] = dim_tanggal['Date'].dt.strftime('%Y-%m')
dim_tanggal['HariNo'] = dim_tanggal['Date'].dt.weekday + 1 # Monday=1, Sunday=7

hari_map = {1: 'Senin', 2: 'Selasa', 3: 'Rabu', 4: 'Kamis', 5: 'Jumat', 6: 'Sabtu', 7: 'Minggu'}
dim_tanggal['Hari'] = dim_tanggal['HariNo'].map(hari_map)

In [37]:
# Membuat dim_pelanggan
dim_pelanggan = df_clean.groupby('customer_id').agg(
    Frekuensi_Transaksi=('invoice_id', 'nunique'),
    Total_Belanja=('nilai_penjualan', 'sum')
).reset_index()

In [39]:
print(dim_tanggal.head(5))

        Date  Tahun  BulanNo Bulan TahunBulan  HariNo    Hari
0 2022-01-01   2022        1   Jan    2022-01       6   Sabtu
1 2022-01-02   2022        1   Jan    2022-01       7  Minggu
2 2022-01-03   2022        1   Jan    2022-01       1   Senin
3 2022-01-04   2022        1   Jan    2022-01       2  Selasa
4 2022-01-05   2022        1   Jan    2022-01       3    Rabu

In [38]:
# Menambahkan logika Segmentasi Pelanggan
def tentukan_segmen(row):
    if row['Frekuensi_Transaksi'] >= 8:
        return 'Loyal'
    elif row['Frekuensi_Transaksi'] >= 4:
        return 'Reguler'
    else:
        return 'Sesekali'

dim_pelanggan['Segmen'] = dim_pelanggan.apply(tentukan_segmen, axis=1)

In [40]:
print(dim_pelanggan.head(5))

  customer_id  Frekuensi_Transaksi  Total_Belanja    Segmen
0           1                    3          46000  Sesekali
1          10                    7         122000   Reguler
2         100                    4          76000   Reguler
3          11                    7          96000   Reguler
4          12                    6         103000   Reguler

**UNIT 6: MENGINTEGRASIKAN DATA (J.62DMI00.011.1)**

In [41]:
# Ekspor seluruh tabel dalam 1 file excel multi-sheet
output_file = "Dataset_Warmindo_Bersih.xlsx"

with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    df_clean.to_excel(writer, sheet_name='Fact_Penjualan', index=False)
    dim_tanggal.to_excel(writer, sheet_name='Dim_Tanggal', index=False)
    dim_pelanggan.to_excel(writer, sheet_name='Dim_Pelanggan', index=False)

**UNIT 7: MEMBUAT BUSINESS INTELLIGENCE (J.62DMI00.015.1)**

1. Membuat Dashboard di Power BI dengan dataset bersih ini.
2. Menyimpulkan rekomendasi dan kesimpulan dari bisnis understandingnya berdasarkan data yang terlihat dalam dashboard Power BI.